import { Nunito } from 'next/font/google';
import Navbar from './components/Navbar';
import Navigation from './components/Navigation';
import "./globals.css";

const nunito =  Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
})

export const metadata = {
  title: "Manikandan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ backgroundImage: 'url(bg-portfolio.jpeg)' }}
        className={ nunito.className }
      >
        <Navbar />
        {children}
        <Navigation />
      </body>
    </html>
  );
}
